name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_IP }}        # 引用 GitHub Secrets 中的 IP
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/qqq_blog
          git pull
          hugo
